import fs from 'fs';
import path from 'path';

export function saveReport(content, outputFile) {
  const outputPath = path.resolve(process.cwd(), outputFile);
  fs.writeFileSync(outputPath, content, 'utf8');
  return outputPath;
}

export function addMetadata(reviewText, meta) {
  const { sourceBranch, destBranch, provider, model, prNumber, diffLength, generatedAt } = meta;

  const lines = [
    '---',
    `<!-- Generated by pr-review on ${generatedAt} -->`,
    `<!-- Provider: ${provider} | Model: ${model} | Diff: ${diffLength} chars | ${sourceBranch} → ${destBranch} -->`,
  ];
  if (prNumber) lines.push(`<!-- PR: #${prNumber} -->`);
  lines.push('---', '');

  return lines.join('\n') + reviewText;
}
